### ISSUE TITLE
Model training on custom dataset

### ISSUE THREAD

**Issue by chillum1718** [dem123456789/HeteroFL-Computation-and-Communication-Efficient-Federated-Learning-for-Heterogeneous-Clients#10]
Hey
I wants to do a custom model training 
For example taking covid, Ctscan and Mri data
Can you please guide me

**Comment by dem123456789** [comment]
I think you can write your own dataset files like the ones in ./dataset/mnist.py, ./dataset/cifar.py. A more clear pipeline I used can be found in [RPipe](https://github.com/dem123456789/RPipe).

**Comment by chillum1718** [comment]
Hey
thanks for reply
can you provide an example with COVID Images dataset
how can we train the moel on covid images and CT MRI dataset
please proovie a running script , it would be great and helpful for me

**Comment by dem123456789** [comment]
Sorry. I don't have access to these resources.

**Comment by chillum1718** [comment]
Hey
tgis is the resource link
https://github.com/ml-workgroup/covid-19-image-repository
