### ISSUE TITLE
the function of stats() in train_classifier_fed.py

### ISSUE THREAD

**Issue by ghost** [dem123456789/HeteroFL-Computation-and-Communication-Efficient-Federated-Learning-for-Heterogeneous-Clients#11]
Hi, thank you for the excellent work. I have a little question, what is the function 'stats' used for? There is a for loop inside to feed data to  the testmodel, however, I don't find the optimizer to update the model and I assume it just "feed" without anything else, then why does it exist. However, when I comment the for loop, the global test accuracy drops, it's weird to me. I appreciate if you can explain it!

**Comment by diaoenmao** [comment]
The stats() is used for computing the statistics used in static batch normalization.
