### ISSUE TITLE
How to continue to train with the checkpoint?

### ISSUE THREAD

**Issue by HideLakitu** [dem123456789/HeteroFL-Computation-and-Communication-Efficient-Federated-Learning-for-Heterogeneous-Clients#13]
Hi, Just try to reproduct experment now.

I Open **config.yml**,  set resume mode in it  like` resume_mode: '0_CIFAR10_label_resnet18_1_10_0.1_non-iid-2_dynamic_a1-b1-c1_gn_0_0_checkpoint.pt'` (the default value is **0**), which the checkpoint file is automatically generated in the folder **output/model** last time, then execute the model again? 

But this seems didn't work, what should I do

**Comment by diaoenmao** [comment]
I am not sure resuming checkpoint is working in this code.
