### ISSUE TITLE
Hello, I have a question about the outlook you mentioned in the article that can be generalized to few-shot learning

### ISSUE THREAD

**Issue by Cmnotjx** [dem123456789/HeteroFL-Computation-and-Communication-Efficient-Federated-Learning-for-Heterogeneous-Clients#7]
I would like to ask whether you mean that the simulation generalization to few-shot learning refers to the few-shot of the communication round between the client and the server or the  few-shot of the relatively small amount of data

**Comment by dem123456789** [comment]
Thanks for your interests. I mean the few-shot of the relatively small amount of data.

**Comment by Cmnotjx** [comment]
> Thanks for your interests. I mean the few-shot of the relatively small amount of data.

Thank you very much for your reply

**Comment by Cmnotjx** [comment]
> Thanks for your interests. I mean the few-shot of the relatively small amount of data.

In addition, I would like to know how this method can be generalized to few-shot learning, and I hope to get your reply

**Comment by dem123456789** [comment]
I made this point in the paper because it is possible for various clients to have unbalanced number of data points. Client with more data may need more local training and model parameters to fully leverage its predicitive power.
